### ISSUE TITLE
Code for the simulated dataset in the slides?

### ISSUE THREAD

**Issue by davidrosenberg** [adith387/SIGIR2016Demo#2]
Hi -- I really enjoyed the SIGIR 2016 presentation.  Does the code in this repo give what's needed to reproduce the experiments discussed in the presentation.  For example, this image:

![image](https://user-images.githubusercontent.com/1561584/111651288-76c35600-87dc-11eb-8602-890d4e2ae115.png)

Thanks!
David

**Comment by adith387** [comment]
Hi David,
Yup! It is just a cross-link of https://www.cs.cornell.edu/~adith/CfactSIGIR2016/Code_Data.zip
Usage instructions are at https://www.cs.cornell.edu/~adith/CfactSIGIR2016/

For the experiment you described, you would run EvalExperiment.py followed by plot_sigir.py

If you find or fix any install/runtime issues (likely due to version mismatches; scikit-learn APIs may have changed from 2016 to now), please submit a PR. Thanks!
--Adith
